esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

substitutions:
  name: pumpkin_1

wifi:
  ssid: !secret ssid
  password: !secret wifi_password

logger:
api:
ota:

switch:
  - platform: template
    name: ${name} On/Off
    icon: mdi:set-center
    id: ${name}_switch
    optimistic: true
    turn_on_action:
      - light.turn_on: ${name}_eyes

    turn_off_action:
      - light.turn_off: ${name}_eyes

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 3
    rgb_order: GRB
    name: ${name} Eyes
    id: ${name}_eyes
    on_turn_on:
      - light.turn_on:
          id: ${name}_eyes
          effect: "Looking"
    effects:
      - addressable_fireworks:
          name: Looking
          update_interval: 1025ms
          spark_probability: 100%
          fade_out_rate: 255