esphome:
  name: pumpkin-1
  platform: ESP8266
  board: d1_mini

substitutions: # Enter the R-G-B colour values here.
  eyes1_red: "255"
  eyes1_green: "128"
  eyes1_blue: "0"

wifi:
  ssid: !secret ssid
  password: !secret wifi_password

logger:
api:
ota:

switch:
  - platform: template
    name: Pumpkin 1 On/Off
    icon: mdi:set-center
    optimistic: true
    turn_on_action:
      - light.turn_on: eyes1
    turn_off_action:
      - light.turn_off: eyes1

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 3
    rgb_order: GRB
    name: Pumpkin 1 Eyes
    id: eyes1
    on_turn_on:
      - lambda: !lambda |
          auto call = id(eyes1).turn_on();
          call.set_brightness(0.5); 
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb((255*0.00001531864)*${eyes1_red},(255*0.00001531864)*${eyes1_green},(255*0.00001531864)*${eyes1_blue});
          call.set_effect("looking");
          call.perform();
    effects:
      - addressable_fireworks:
          name: Looking
          update_interval: 1025ms # 'Looking' Left-Right speed
          spark_probability: 100%
          fade_out_rate: 255
